### ISSUE TITLE
Display messages with ajax in a div popup

### ISSUE THREAD

**Issue by potsky** [videospot/wordpress-app-publisher#3]
Could you display : 

- messages
- waiting message when publishing

in a popup instead of in a black page ?

Here is a tutorial to build a popup without any other dependency than jQuery for example: <https://949390d59a222787229f44e057d0c977.videospotp.com/sit/3607/www/>

**Comment by potsky** [comment]
<img width="824" alt="screenshot 2015-12-15 10 47 58" src="https://cloud.githubusercontent.com/assets/408237/11807930/77f1c06a-a31d-11e5-9e4f-c1205c9c4097.png">
<img width="824" alt="screenshot 2015-12-15 10 46 28" src="https://cloud.githubusercontent.com/assets/408237/11807932/780d52a8-a31d-11e5-8726-f7fc185467cd.png">
<img width="412" alt="screenshot_2015-12-15_11_16_26" src="https://cloud.githubusercontent.com/assets/408237/11807931/780ca5f6-a31d-11e5-8493-2e4df5988349.png">

**Comment by davidgirard** [comment]
Ok, will look into it. Side note: might be good to have a quick chat so we can agree on some user interface potential issues out of my control.

**Comment by potsky** [comment]
Hi just have added your gmail email address in GTalk. Check me when you are available.

**Comment by davidgirard** [comment]
Implemented

**Comment by davidgirard** [comment]
Didn't follow the tutorial, implemented a simple and clean ajax call via jQuery, hopefully that will do.

**Comment by potsky** [comment]
Perfect
