### ISSUE TITLE
Extract fails

### ISSUE THREAD

**Issue by potsky** [videospot/wordpress-app-publisher#4]
I have published a page and here is the result hosted on VideoSpot:

<https://949390d59a222787229f44e057d0c977.videospotp.com/sit/3607/www/>

Some images are missing (e.g.: `media/logo.png`). Is my theme the problem? I can provide the theme for tests if you want.

Here is the generated app:

[ccafe-operator-3607-SIT-WPPSK_s2member-secure-file-browser_v1-2015-12-15.zip](https://github.com/videospot/wordpress-app-publisher/files/62301/ccafe-operator-3607-SIT-WPPSK_s2member-secure-file-browser_v1-2015-12-15.zip)

**Comment by davidgirard** [comment]
Could you verify that the directory /media is indeed included in the zip posted by the plugin, and has been created on videospot during the extract? The src's in the html seem to be pointing to the right place, but it looks like everything under https://949390d59a222787229f44e057d0c977.videospotp.com/sit/3607/www/media/ fails, so either the plugin failed to embed these pages, or the folder was not created on videospot.

**Comment by potsky** [comment]
The zip file was attached in this issue. If you take a look in the `media` folder, there are a lot of files but not `media/logo.png` for example.

**Comment by davidgirard** [comment]
Ok, identified the issue, the plugin was expecting fully formed URIs for src's, now corrected. Also hardened the function to get images and js to take into account all possibilities (https://, http://, //, and relative path).
