### ISSUE TITLE
Extract fails when using op

### ISSUE THREAD

**Issue by potsky** [videospot/wordpress-app-publisher#8]
The plugin publishes an empty app (with app skeleton only, no media, etc...) on a wordpress instance. It seems there is a problem with Curl when `open_basedir` is set on the server.

```
[Fri Jan 08 10:23:20 2016] [error] [client 88.191.1.74] PHP Warning:  curl_setopt(): CURLOPT_FOLLOWLOCATION cannot be activated when an open_basedir is set in /home/wpvswww/app/wordpress/wp-content/plugins/videospot-app-publisher/includes/remote-post.inc on line 135, referer: https://www.videospot.com/wp-admin/post.php?post=5917&action=edit
[Fri Jan 08 10:23:20 2016] [error] [client 88.191.1.74] PHP Warning:  DOMDocument::loadHTML(): Empty string supplied as input in /wordpress/wp-content/plugins/videospot-app-publisher/includes/remote-post.inc on line 182, referer: https://www.videospot.com/wp-admin/post.php?post=5917&action=edit
```

**Comment by davidgirard** [comment]
Quick test to see whether open_basedir is enforced. Might need longer term solution if both open_basedir and redirects are used, but likelihood is low (interestingly, the open_basedir + CURLOPT_FOLLOWLOCATION incompatibility is actually a bug, there is no reason follow location should be a security issue when open_basedir is enforced if implemented correctly, lazy quick fix to avoid a potential security issue, never been fully addressed by php). If test successful please close, and open an enhancement request for the longer term solution.

**Comment by potsky** [comment]
I have manually written the curl redirect, it is ok now.
